### ISSUE TITLE
Invalid HTTP_HOST header error on production

### ISSUE THREAD

**Issue by cyanfish** [krystjan/heltour#14] opened 2016-07-31 03:01 UTC
Full error message:
`Invalid HTTP_HOST header: '173.230.151.075'. You may need to add u'173.230.151.075' to ALLOWED_HOSTS.`

Seems to occur a few times a day for no particular reason.

**Comment by chris--** [comment] 2016-07-31 08:58
Could these errors stem from crawlers/robots that prope the IP instead of the DNS name?

**Comment by lakinwecker** [comment] 2016-07-31 16:05
Should be fixed.

**Closed by lakinwecker** 2016-07-31 16:05 UTC

**Comment by lakinwecker** [comment] 2016-07-31 21:08
For the record, that is the cause of the errors. I usually have my front-end servers setup so that unless it's a valid hostname the url 404's immediately, but in this case the heltour app was the default one for these requests, and django will complain about them if the domain doesn't match the ones in the settings.
